### ISSUE TITLE
Partial search

### ISSUE THREAD

**Issue by MaraScott** [YousefED/ElasticUI#102]
Hi, 

is the partial search (like regex in Kibana 'stringtosearch*') can be configured in the elasticUI or is it somewhere else ?

thanks

**Comment by tolgap** [comment]
Don't use the `<eui-query/>` directive, but implement it manually like this:

```html
<input type="text" eui-query="ejs.WildcardQuery('surname', '*' + surname + '*')" ng-model="surname" eui-enabled="surname.length" />
```
