### ISSUE TITLE
Ability to set pageSize

### ISSUE THREAD

**Issue by lukewertz** [YousefED/ElasticUI#18]
I have a use-case where I want to display results in increments other than 10. I don't see any way to change the pageSize for the initial request. It seems odd aggregation sizes can be set but query sizes cannot. Would it be difficult to implement a .size() option on queries?

**Comment by mastermind1981** [comment]
@YousefED Is it possible to merge this pull request?

**Comment by YousefED** [comment]
There are some issues described in #19 that I'd like to fix first
