### ISSUE TITLE
Multiple eui-query in same html

### ISSUE THREAD

**Issue by lauraltamiranos** [YousefED/ElasticUI#23]
I have 2 eui-query with an input tag in same html doc. 2nd one is created after I search in the 1st one.

After searching in the 1st one, results are shown, however after the 2nd one is activated/created, elasticUI does a MatchAll behind scenes and results from the previous search are gone and I would like to keep them in my screen.

Is there a way to disable the MatchAll in this case?

**Comment by YousefED** [comment]
I think the only way to accomplish this is to have two eui-index directives, therefor setting up two ElasticUI-scopes.

I haven't tried this before, so let me know how it works.

**Comment by lauraltamiranos** [comment]
Thank you very much for your answer!

I restructured the app and broadening the scope of 1st eui-query and then only updating ng-model when the new search has to be performed gives a good result, therefore avoiding 2 eui-query's in this case

**Comment by mindnervestech** [comment]
HI lauraltamiranos ,
how did you solve issue?

**Comment by molchwien** [comment]
Yeah, how does one solve this issue?
+1
