### ISSUE TITLE
Force refresh?

### ISSUE THREAD

**Issue by rgauny** [YousefED/ElasticUI#25]
Great plugin btw! But I have an issue trying to refresh once I have done a soft delete on an item in my list.

Currently trying in my controller without luck:
  $scope.deleteRun = function (doc) {
                if(confirm("Are you sure you want to delete this run?")){
                    es.client.update({
                        index: 'jmeter-event',
                        type: 'jmeter-event',
                        id: doc._id,
                        body: {
                            doc: {
                                deleted: true
                            }
                        }
                    }, function (error, response) {
                        $scope.indexVM.refresh();
                        console.log(response);
                    });
                }
            };

Inside the refresh I do see that the item gets re-queried and the deleted value is set to true but the fields on my screen that are binded to the delete value do not change unless i reload the entire page.
<a  class="delete-button text-error" ng-click="deleteRun(doc)" href="#">delete {{doc._source.deleted}}</a>

Any suggestions?

**Comment by YousefED** [comment]
Thanks. The indexVM.refresh method currently only updates the model if the document count changes. It might be a good idea to add a force_deep_refresh parameter to this method for your scenario.

You could also update the document manually when receiving the updated version in your success handler.

**Comment by YousefED** [comment]
you can now call indexVM.refresh(false) to force a complete refresh
