### ISSUE TITLE
Add enabled filter?

### ISSUE THREAD

**Issue by rgauny** [YousefED/ElasticUI#26]
How do I add a filter in code which is enabled by default...

I added by the checkbox method and that works but I just want to do it in my controller. Is this possible?

this is what worked:
<input type="checkbox" eui-filter="ejs.TermsFilter('deleted', 'false')" ng-model="filter.enabled"> Hide deleted

but i want to enable in code in controller

**Comment by YousefED** [comment]
You can set filter.enabled to true or use the attribute eui-enabled. See:

https://github.com/YousefED/ElasticUI/blob/master/docs/components.md

If this is not clear, please share a code sample where you're having issues

**Comment by rgauny** [comment]
Hi Yousef!

  My issue is I don't know how to properly reference the filters.enabled
property in my controller. I have tried $scope.filters.enabled = true; but
that is undefined.

Any thoughts on how I can reference and what I may be doing wrong here?

**Comment by YousefED** [comment]
2 things:
- The object is "filter", not "filters"
- You'll need to reference the scope created by the eui-filter directive. This is a new scope defined on the element where you've added the directive

**Comment by rgauny** [comment]
Sorry man still confused here and new to angular. Is below what your talking about because this doesnt work either.

mpafApp.controller("RunController", function($scope, es, esFactory) {
           angular.element("#myFilter").scope().filter.enabled = true;
}

and in html
<input id="myFilter" type="checkbox" eui-filter="ejs.TermsFilter('deleted', 'false')" ng-model="filter.enabled"> Hide deleted
