### ISSUE TITLE
Accessing querystring from the controller

### ISSUE THREAD

**Issue by mastermind1981** [YousefED/ElasticUI#28]
Hi,

I'm using the searchbox directive and i want to watch the querystring variable in my controller. The problem is that inside my controller when i make $scope.querystring is not recognized.
but when access to it through this it works !!!
 so when i make my watch like that  it does not work:

                  $scope.$watch('querystring', function(newValues, oldValues) {
                  });

Thank you.

**Comment by YousefED** [comment]
I suggest creating your own querystring variable and binding eui-query to that. You can then watch the source wherever you like!

**Comment by YousefED** [comment]
You could also watch indexVM.query but this might change in a future release

**Comment by mastermind1981** [comment]
thank you i will give it a try
