### ISSUE TITLE
improved pagination

### ISSUE THREAD

**Issue by mastermind1981** [YousefED/ElasticUI#36]
Hi Yousef,

I want to share how i did pagination with elastic ui: I used [Angular-pagination](https://github.com/brantwills/Angular-Paging). 

Pagination is done like this :  

```
				<div paging
					ul-class="pagination pagination-lg"
					page="indexVM.page" 
					page-size="indexVM.pageSize" 
					total="indexVM.results.hits.total"
					adjacent="1"
					dots="..."
					scroll-top="true" 
					hide-if-empty="true"
					show-prev-next="true">
				</div>	
```

**Comment by ztoliver** [comment]
Any chance of a PR for this if it works? Would like to have advanced pagination in my application.

**Comment by mastermind1981** [comment]
@ztoliver there is the default pagination shipped with ElasticUI. But for a customized  or more advanced pagination you can use whatever library. You have the elements via the IndexVM

For me I have used Angular-pagination : I have added the depedency , the module to the application and lastly the html in the comment above.

**Comment by YousefED** [comment]
Agree with @mastermind1981
