### ISSUE TITLE
on drag start?

### ISSUE THREAD

**Issue by johnrfrank** [YousefED/ElasticUI#37]
Yousef,  thanks for the amazing tools.

What is the best way to call setData on drag start of a result in the elasticui result list?

Something like this jsfiddle:  http://jsfiddle.net/4LeyLp2s/

```
        $item.on('dragstart', function(ev) {
            var fcId = $item.data('feature-collection-id'),
                fc = fcs[fcId],
                data = ev.originalEvent.dataTransfer;
            data.setData('features', JSON.stringify(fc));
```

**Comment by YousefED** [comment]
Thanks John. You can do this the same way as you'd do for any dynamically rendered Angular item. I'd search for "angular drag and drop". If there's anything elasticui specific you're running into, let me know.

**Comment by johnrfrank** [comment]
Right, we understand how to use drag and drop.  The thing we don't understand yet how to do is attach to the elements that are generated by elasticui.  

If we have a line like this:
<li class="list-group-item ng-scope" ng-repeat="doc in indexVM.results.hits.hits track by $index">

how do we attach to the items generated by indexVM?
