### ISSUE TITLE
Saving filters and search results when navigating away from page

### ISSUE THREAD

**Issue by eriadam** [YousefED/ElasticUI#39]
I have a fully working solution with ElasticUI, a product search page where the user can filter for price, brand, features, free text search, etc. The problem is, when navigating to the detail page of a product then back to the list, the previously set filters are gone.

Is there a way to persist the previously selected facets, the search results and the page number where the user was last?

**Comment by YousefED** [comment]
Thanks for the idea. To accomplish this you'd need to integrate an Angular URL Routing library into your app. At this moment, we don't have any plans to integrate this directly into ElasticUI

**Comment by joshbedo** [comment]
Also curious about this one. Right now i need to persist the filters applied via something like localstorage and their doesn't appear to be an easy way to achieve persistence with filters.

**Comment by YousefED** [comment]
I agree it would be a great addition, but I don't have any plans to integrate this myself.

Definitely welcome any PRs for this one though
