### ISSUE TITLE
Searchbox now showing

### ISSUE THREAD

**Issue by janpetras** [YousefED/ElasticUI#41]
Hello

I've followed all the steps needed, and exactly followed the JSFiddle also, but no matter what I do, ElasticUI won't play ball with Pencilblue.

I'm thinking the module might not be loaded properly or something. Is there any way to check this? You can check http://henleymcc.herokuapp.com/ to see that all the files required are loaded in the head, the index is defined on the body, and the searchbox is defined in the HTML above the 'TEST' span (upper right menu, under Courses) but the searchbox is not showing.

I've checked the JSFiddle and the searchbox should basically load even without any sort of additional config (such as the .constant, the host, the index, etc.). All you need in JSFiddle to get it to load is to have the required .js files in the head and an angular.module 'elasticui' defined and loading, and it will show.

But not for me. I'm wondering why would that be.

**Comment by mastermind1981** [comment]
you don't have elasticsearch.angular.js in your js dependencies:

add to your dependencies.

**Comment by YousefED** [comment]
Also, have you defined 

angular.module('yourApp', ['elasticui']).constant('euiHost', 'http://localhost:9200');

as described on the project docs?

**Comment by janpetras** [comment]
Hi.

The problem was that elasticui was not properly declared.

Pencilblue uses var angularController = "var pencilblueApp = angular.module('pencilblueApp', " + JSON.stringify(modules) + ") and what I had to do was basically this: var angularController = "var pencilblueApp = angular.module('pencilblueApp', " + JSON.stringify(modules) + ").constant('euiHost', 'localhost:9200')";

And also add 'elasticui' in the modules=['ngRoute') array, and remove an if declaration to make sure it's loaded.

Basically, you can see what I'm talking about here: https://github.com/pencilblue/pencilblue/blob/master/include/client_js.js between lines 40 and 45.

I don't know of a better way to do it in this context, other than removing         if(!util.isArray(modules) || modules.length === 0) {
            modules = ['ngRoute'];
        } and leaving just the modules = ... declaration, and then modifying line 45 as described above.

It's working now, but I think I broke Pencilblue in the process.

Sorry for bothering, hope this helps others trying out ElasticUI with PencilBlue
