### ISSUE TITLE
Question : how to change enabled flag from scope.

### ISSUE THREAD

**Issue by mastermind1981** [YousefED/ElasticUI#42]
Hi ,

I have seen in the doc that i can change for example filter.enabled from scope. Is it possible? The directive uses an isolate scope.

thanks

**Comment by YousefED** [comment]
This page has an example: https://github.com/YousefED/ElasticUI/blob/master/docs/components.md (see euiFilter).

The scope is an inherited scope, and from code within the same scope (e.g.: child elements) you can modify the value. In the example ngModel is used to bind to scope.filter.enabled

**Comment by mastermind1981** [comment]
May be my question wasn't clear enough : my goal to enable/disable the enabled flag from parent controller. I don't know if it is possible or not.

I created a variable in the parent controller scope (the controller of the view containing the filter directive) which will be used to set the enabled flag on the filter, i have call it enableXFilter .

And  i have used it like this:
```
 <label class="btn " ng-change="filter.enabled = enableXFilter " ng-model="enableXFilter"
                eui-filter="ejs.TermFilter('field','value')"  btn-checkbox>
```
When the button is checked enableXFilter and filter.enabled are correctly setted. But the problem is that  the enableXFilter in the parentController scope isn't impacted. Actually, it's a scoping a problem, but i thought that eui-filter directive uses scope =true inherited scope and it will use the enableXFilter declared within the parent scope variable.

Am i missing something in my approach?

**Comment by YousefED** [comment]
Isn't this the famous angular issue with changing primitive variables? Try declare enableXFilter on an object, e.g. ng-model="wrapper.enableXFilter" etc.

**Comment by mastermind1981** [comment]
Good eye!! it works شكرا جزيلا
