### ISSUE TITLE
Filter Results by field not working

### ISSUE THREAD

**Issue by cthomas1978** [YousefED/ElasticUI#43]
This is an issue on my part but I'm really struggling trying to get this working.  I am using your demo as a template and want a multiselect filter that can be checked to filter down the results based on an indexed field.  The field in the index is _index.  Essentially I have several indexes, one for each site indexed in ES and want to be able to filter the results by index. 

This is the code that pulls a list of indexes and the number of results per index:

    <ul class="nav nav-list" eui-aggregation="ejs.TermsAggregation('sitefilter').field('_index').size(5)">
		        <li ng-repeat="bucket in aggResult.buckets">
		    	    <label class="checkbox" eui-filter="ejs.TermsFilter('_index', bucket.key)">
			    <input type="checkbox" id="sitefilter{{bucket.key}}" >
			    <label for="sitefilter{{bucket.key}}">{{bucket.key}} ({{bucket.doc_count}})</label>
			</label>
		    </li>
		</ul>

When selected, they do nothing to the results.  What am I missing?

I apologize if this is a trivial thing.  I'm a newb to ES and ElasticUI.  Thank you in advance.

**Comment by YousefED** [comment]
try changing:
<input type="checkbox" id="sitefilter{{bucket.key}}" >
to
<input type="checkbox" id="sitefilter{{bucket.key}}" ng-model="filter.enabled">
