### ISSUE TITLE
Getting this Error

### ISSUE THREAD

**Issue by OElesin** [YousefED/ElasticUI#44]
XMLHttpRequest cannot load http://localhost:9200/cases/_search?size=10&from=0. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

How do I fix this?

**Comment by mastermind1981** [comment]
You should enable cors in your ES server (elasticsearch.yml). The readMe says
 > If you are not serving the demo page from Elasticsearch you might have to enable CORS and allow requests to Elasticsearch from your host.

```

http.cors.enabled : true
http.cors.allow-origin : "*"
http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length
```
