### ISSUE TITLE
Having trouble with ejs.sort().geoDistance Objekt

### ISSUE THREAD

**Issue by roederb** [YousefED/ElasticUI#45]
Hi everyone,
perhaps someone can help with some "syntax-issue"?. I'm trying to sort my index result by distance to a given geopoint with following syntax:

div eui-sort="ejs.Sort().geoDistance(Location('49.8218,11.06')).order('asc')" eui-enabled="true"></div

where Location is the GeoPoint within the index which stores the geodata of my docs.

if i use the syntax as described for the sort-componente (something like div eui-sort="ejs.Sort('Name')order('asc')" eui-enabled="true"></div) everything seems to be fine.

any help is appreciated.

cheers

**Comment by YousefED** [comment]
- What kind of error do you get?
- does the ejs sort result in a valid JSON sort when executed in the console?

**Comment by roederb** [comment]
Hi thanks for your response,
item has been solved meanwhile, 
div eui-sort="ejs.Sort('Location').geoDistance(ejs.GeoPoint([0.0,0.0])).unit('km').distanceType('plane').order('asc')" eui-enabled="true"></div

was the solution
