### ISSUE TITLE
Highlight multible fields

### ISSUE THREAD

**Issue by macb74** [YousefED/ElasticUI#51]
Hi,

trying to highlight multible fields like this: eui-highlight="ejs.Highlight(['subject', 'textContent']).preTags('<mark>').postTags('</mark>')

But, does not work. Any tip for me?
Thanks
Martin

**Comment by YousefED** [comment]
Hi,

I'd recomment inspecting the request sent to elasticsearch and received from it, to see where the issue is

**Comment by barthevandoorn** [comment]
I am using highlight syntax... eui-index="'myesindex'" eui-highlight="ejs.Highlight('field1','field2').preTags('<b><mark>').postTags('</mark></b>')" eui-enabled="true"

the elasticsearch log shows ,"highlight":{"fields":{"field1":{}},"pre_tags":["<b><mark>"],"post_tags":["</mark></b>"]}}],

I am seeing highlights on single field.. but when I add 2nd field, only first field is highlighted.  

What is the correct syntax to enable highlights for multiple fields

**Comment by YousefED** [comment]
Please see: http://docs.fullscale.co/elasticjs/ejs.Highlight.html

- pass in the fields as an array
