### ISSUE TITLE
eui-singleselect with exact match for field, not split

### ISSUE THREAD

**Issue by devads** [YousefED/ElasticUI#55]
Hi,

I'd like to know if it's possible for eui-aggregation, eui-singleselect, ... to get the full value of the field and not split it and lowercase it.

Thanks,

**Comment by YousefED** [comment]
This depends on the analyzer configured in your elasticsearch mapping. set a field to "not_analyzed" and this won't happen.

**Comment by devads** [comment]
Yes I finally found the solution yesterday !
Sorry I just began elasticsearch 3 days ago.
Thanks !
