### ISSUE TITLE
Order aggregation

### ISSUE THREAD

**Issue by devads** [YousefED/ElasticUI#57]
Hi,

I'm not sure it's implemented, is it possible to order the aggregation ?
like in the doc of elastic.co
{
    "aggs" : {
        "genders" : {
            "terms" : {
                "field" : "gender",
                "order" : { "_term" : "asc" }
            }
        }
    }
}

Thanks,

**Comment by YousefED** [comment]
Yes, just create the aggregation with an order, should be possible with https://github.com/fullscale/elastic.js/
