### ISSUE TITLE
Filter on Multiple Indexes

### ISSUE THREAD

**Issue by pezzell** [YousefED/ElasticUI#59]
I have added an alias to the eui-index as well as the _index field to the singleselect field.

<body ng-app="tutorial" eui-index="'allindexes'">

<eui-singleselect field="'_index'" size="5"></eui-singleselect>

However, filtering on the index name does not return any results.  Is there a way to filter on the index name?

I believe the query would need to look something like this:

"query": {
    "indices": {
      "indices" : ["tweets"],
      "query": {
        "match_all": {}
      }, 
      "no_match_query" : "none"
    }
  }

**Comment by YousefED** [comment]
The query system in ElasticUI uses https://github.com/fullscale/elastic.js/, which might not support this. If so, we'd need to upgrade to regular ElasticSearch JSON syntax for queries

**Comment by pezzell** [comment]
Thanks.  I was able to get it to work.  I updated the template for the singleselect

```
<label eui-filter="ejs.Request().query(ejs.IndicesQuery(ejs.MatchAllQuery(), bucket.key).noMatchQuery(\'none\'))">
```
