### ISSUE TITLE
Get result of Aggregation directly in JS

### ISSUE THREAD

**Issue by devads** [YousefED/ElasticUI#61]
Hi,

I tried to get the result of an aggregation directly in JS but without success.

var maxRes = ejs.MaxAggregation('max_price').field('price.raw');

But I dont know how to execute the aggregation and get the result.

Do you think it's possible ?

Thanks,

**Comment by YousefED** [comment]
This is not related to ElasticUI, I'd check out elasticsearch-angular or Fullscale/ElasticJS

**Comment by devads** [comment]
Ok thanks !
