### ISSUE TITLE
Pinned Filters

### ISSUE THREAD

**Issue by fsattar** [YousefED/ElasticUI#63]
Hey @YousefED,

We have a use case where our users would like their filters pinned. Is that on the horizon? If not could you please give me some direction on how you would go about persisting filters to local storage. Would love to send you a PR.Thanks.

**Comment by YousefED** [comment]
Hi, I'm not planning to implement this myself at the moment.

In theory, you should be able to capture and save the values of eui-filter (and possible eui-sort, eui-aggregation and then load those from storage
