### ISSUE TITLE
Custom Ordering for Checklist and SingleSelect

### ISSUE THREAD

**Issue by cricket007** [YousefED/ElasticUI#65]
From what I understand, the SortDirective only works on document attributes in the Elastic documents and the current implementation for the Checklist and SingleSelect Directives simply to ascending alphabetic ordering on `bucket.key`. 

Is it possible to add an Angular `orderBy` to the `ngRepeat` for custom ordering? For example, I would like to sort the `bucket.doc_count` in a descending order for both those Directives.

**Comment by YousefED** [comment]
Yes, we recommend using the base components instead of the widgets. Please review the first few paragraphs at https://github.com/YousefED/ElasticUI/blob/master/docs/widgets.md. 

Hope this helps!
