### ISSUE TITLE
Question regarding SingleselectDirective

### ISSUE THREAD

**Issue by ragogitpub** [YousefED/ElasticUI#67]
Hello

Wondering if somebody can answer this newbie question.

Where does the filter.enabled come from in SingleselectDirective ?

I am trying to create a new widget DtSingleselectDirective to get date aggregations. I made a copy of it like below.

The problem that happens is that filter.enabled is not defined and only the !filter.enabled is rendered. When I click on one of the aggregations then for a brief moment filter.enabled is available but when the ES response arrives and things are re-rendered only the first ng-if ( !filter.enabled ) is rendered.

Any thoughts ?

module elasticui.widgets.directives {
    // The widgets show how to create reusable components on top of ElasticUI. 
    // You can also directly use the directive.template html in your front-end (see docs/widgets.md for more info)
    export class DtSingleselectDirective {
        static $inject = ['$parse'];
        constructor($parse) {
            var directive: ng.IDirective = {};
            directive.restrict = 'E';
            directive.scope = true;

            (<any>directive).link = {
                'pre': function (scope, element, attrs: any) {
                    elasticui.util.AngularTool.setupBinding($parse, scope, attrs, ["field", "size"]);
                    scope.agg_name = scope.field.replace(/[^a-z_0-9]/gmi, "_") + "_" + (default_agg_count++);
                }
            }

            directive.template = '\
		<ul class="nav nav-list" eui-aggregation="ejs.DateHistogramAggregation(agg_name).field(field).interval(\'day\').minDocCount(1)">\
	                <li ng-repeat="bucket in aggResult.buckets">\
        	            <label eui-filter="ejs.RangeFilter(field).from(bucket.key).to(aggResult.buckets[$index + 1].key)">\
	                        <span ng-if="!filter.enabled"><a href="" ng-click="filter.enabled=true">{{ bucket.key_as_string | date:\'MM/dd/yyyy\' }} <span class="muted">({{bucket.doc_count}})</span></a></span>\
	                        <span ng-if="filter.enabled">{{bucket.key_as_string | date:\'MM/dd/yyyy\'}} <a href="" ng-click="filter.enabled=false" class="facet-remove">x</a></span>\
        	            </label>\
	                </li>\
		</ul>'
            
            return directive;
        }
    }
    directives.directive('euiDtSingleselect', DtSingleselectDirective);
}

**Comment by YousefED** [comment]
all the filter.* properties are added to the scope by eui-filter directive. Also see: https://github.com/YousefED/ElasticUI/blob/master/docs/components.md

Hope this helps,
