### ISSUE TITLE
Multiple indices

### ISSUE THREAD

**Issue by kalwar** [YousefED/ElasticUI#70]
How do you add multiple indices?
if I have 'testindex', 'testindex2' etc

Can I do something like this?
eui-index="'testindex', 'testindex2'"

**Comment by YousefED** [comment]
This is currently not supported I think. You could make an alias in Elasticsearch to point to multiple indices

**Comment by kalwar** [comment]
Thanks for your kind response. 
How do I create "alias in Elasticsearch"?

**Comment by YousefED** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html
