### ISSUE TITLE
Using elasticiu on the REST API

### ISSUE THREAD

**Issue by Guisardo** [YousefED/ElasticUI#71]
Hi there,
I really like elasticui, but to be able to put it in production I need some way to set that all the querys had to be done by GET to the search REST API of elastic search. This allow me to use cache systems like varnish and also allow me to secure the elasticsearch cluster.
Is this possible? How may I help to make this possible?
Best,

**Comment by osterman** [comment]
I'm looking into this right now. I am using NodeJS+express so tried using express-http-proxy to pass `GET` and `OPTIONS` on `/<index>/*`, but no luck.

**Comment by YousefED** [comment]
Hi. What is the exact issue / error? ElasticUI was designed for the REST api and should work seemlessly with it. It hasn't been tested on elasticsearch 2+ yet though, maybe there's an issue there?

**Comment by Guisardo** [comment]
Hi @YousefED , this is more of a question then. How can we use ElasticUI only with using the GET method instead of the POST? Can you add some example to the docs?
Best,

**Comment by YousefED** [comment]
not possible I think:

http://stackoverflow.com/questions/22535324/nodeelasticsearch-sending-a-body-on-a-get-request
https://github.com/elastic/elasticsearch-definitive-guide/issues/64

Recommended to configure your proxy to only allow requests (incl. POST) to /_search/

**Comment by Guisardo** [comment]
The problem is that POST are not cacheable. So personally I had end up using directly the search method of elasticsearch.js:
https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-search

Sending the q instead of the body makes the request by GET. Although it works, I'd to make the queries manually. Is there any way to use this method with ElasticUI ?
