### ISSUE TITLE
Query on nested fields

### ISSUE THREAD

**Issue by fabiana001** [YousefED/ElasticUI#82]
Hi,
I did not find a way for searching into nested fields. I tried to insert into "field" attribute the path expressed in dot notation, as in the following:

`<eui-singleselect field="'focusLocation.cityName'" size="5"></eui-singleselect>`

Does it exist a way to do this?

Thanks

**Comment by YousefED** [comment]
In general we recommend using raw components instead of the prebuilt widgets: https://github.com/YousefED/ElasticUI/blob/master/docs/components.md. That should make it possible

**Comment by jenswitzel** [comment]
@fabiana001 Did you find out? I'm going around in circles. #-) 

Try to build things like this in ElasticUI:
`curl -k -XGET 'https://somehost/some_collection/some_type/_search?&pretty=true&size=3' -d '{
        "size": 0,
        "aggs": {
                "subjects-aggs-raw": {
                        nested: {
                                path: "subjects"
                        },
                        aggs: {
                                subject-agg-raw: {
                                        terms: {
                                                "field": "subjects.subject.raw"
                                        }
                                }
                        }
                }
        }
}'`

I tried: 

```
 <ul eui-aggregation="ejs.TermsAggregation('subjects').field('subjects.subject.raw').path('subjects')">
                        <li ng-repeat="bucket in aggResult.buckets">{{bucket}}...{{bucket.key}} {{bucket.doc_count}}</li>
                </ul>

```
