### ISSUE TITLE
dynamically increase aggregation size (i.e., "show more")

### ISSUE THREAD

**Issue by maxmelnick** [YousefED/ElasticUI#9]
First of all, great work with ElasticUI - very useful!

What would be the easiest way to add the capability for the user to click a button to show more aggregation values?  For example, when the search initially loads, a user sees the top 10 hashtags listed as aggregations/filter options.  What if the user wants to change the display so they can see the top 20 hashtags instead?

**Comment by the666bbq** [comment]
hi,
I modified this to :
`<div ng-repeat="bucket in aggResult.buckets" ng-show="$index<limits">`

with toggling/collapsing (all/size vs minimum) done by :
`<div ng-show="aggResult.buckets.length>limit_min">
<a href="" ng-click="limits=size" ng-show="size>limits">--more--</a>
<a href="" ng-click="limits=limit_min" ng-show="limits==size">--less--</a>
</div>`

This way "more" does not trigger a requery, just for collecting a bigger bucket (size). However I planned to set limit_min as an attribute of my new directive (have an ng-init for now) but it does not seem to be binded to the scope in the pre/link function of the directive definition :
`elasticui.util.AngularTool.setupBinding($parse, scope, attrs, ['field', 'size', 'limit_min']);`
Is that not what you used this setupBinding for ??

**Comment by YousefED** [comment]
no, setupBinding takes attributes from attrs and binds them on the scope. limit_min in your case is not an attribute

**Comment by the666bbq** [comment]
thx for looking into this Yousef.
I forgot the mention :)
`<eui-multi-select-filter field="'someFacet'" size="100" limit_min="6" />`

I thought this way the limit_min value would be picked up setupBinding as I listed the attribute in the array (in the directive) to be setup, and set to the new variable binded to the scope ? Or can I pass this attribute somewhere else ?

**Comment by ms8779** [comment]
Hi Yousaf brother. Is there a way that i can preserve the state of my filter when i routes the pages from one to other and return back to search again.
